### ISSUE TITLE
Federation not supported?

### ISSUE THREAD

**Issue by KHajek-tricentis** [vurhanau/csharp-spiffe#195]
I have a client on trust domain `example.org` calling a server on trust domain `example2.org`. I set up federation on both spire servers and copied trust bundles between the servers. When the client calls the server I'm getting 
`      System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> Spiffe.Bundle.BundleNotFoundException: Bundle not found for trust domain 'example2.org'
         at Spiffe.Bundle.X509.X509BundleSet.GetX509Bundle(TrustDomain trustDomain) in /src/src/Spiffe/Bundle/X509/X509BundleSet.cs:line 36
         at Spiffe.WorkloadApi.X509Source.GetX509Bundle(TrustDomain trustDomain) in /src/src/Spiffe/WorkloadApi/X509Source.cs:line 101
         at Spiffe.Svid.X509.X509Verify.Verify(X509Certificate2 leaf, X509Certificate2Collection intermediates, IX509BundleSource bundleSource) in /src/src/Spiffe/Svid/X509/X509Verify.cs:line 45
         at Spiffe.Ssl.SpiffeSslConfig.ValidateRemoteCertificate(X509Certificate cert, X509Chain chain, IX509BundleSource x509BundleSource, IAuthorizer authorizer) in /src/src/Spiffe/Ssl/SpiffeSslConfig.cs:line 90`

Looking at the code, seems like `X509Source` loads only a bundle for the local trust domain?

**Comment by vurhanau** [comment]
Federation should be supported ([TestWorkloadApiClient.TestWatchX509Context](https://github.com/vurhanau/csharp-spiffe/blob/b018b91698b7fb55ed9528fb3d8ff4202dc49e93/tests/Spiffe.Tests/WorkloadApi/TestWorkloadApiClient.cs#L440)).

Could you set trace log level in workload client to check if bundle is streamed down from the Spire agent? Bundles should be logged [here](https://github.com/vurhanau/csharp-spiffe/blob/b018b91698b7fb55ed9528fb3d8ff4202dc49e93/src/Spiffe/WorkloadApi/WorkloadApiClient.cs#L301).

**Comment by vurhanau** [comment]
If I remember correctly, there are 2 ways to distributed federated trust bundles in SPIFFE:
1. SPIFFE server in your trust domain consumes foreign SPIFFE server trust bundle.
 Then foreign trust bundle is streamed down to workloads in your trust domain.
2. Workload itself consumes federation endpoint of the foreign trust domain SPIFFE server (like [spiffe/go-spiffe](https://github.com/spiffe/go-spiffe/tree/87cfecf6c092ad3c94862bf21c34bf72074d118a/v2/federation))

Scenario 1 should be supported (unless there is a bug).
Scenario 2 is not supported currently.

**Comment by KHajek-tricentis** [comment]
Thanks for quick response. The issue was on my side, I forgot to add `-federatesWith` flag to the workload registration entry.
